define(['require', 'app'], function(require, APP) {

    /**
     * Controller for NOTE_EDIT generated by Appery.io
     * @module NOTE_EDIT
     */

    APP.controller('NOTE_EDIT', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];

            var requestData = {};
            requestData = (function mapping2236($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('NOTES_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|C20A7E99-5596-4084-A194-4CA4E8B7C0AA||2236|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("NOTES_get")(requestData).then( /*|service_bookmark|bookmark|C20A7E99-5596-4084-A194-4CA4E8B7C0AA||4873|*/

            function(success) { // success callback
                (function mapping2565(success, $scope) {
                    var NOTE_scope = $scope.NOTE;
                    NOTE_scope = success;
                    $scope.NOTE = NOTE_scope; /*|button_mapping|onsuccess|C20A7E99-5596-4084-A194-4CA4E8B7C0AA||2565|*/

                    $scopoe.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            var requestData = {};
            requestData = (function mapping8587($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('NOTES_update.request.data', undefined, true);

                var NOTE_scope = $scope.NOTE;
                requestData.DBID = NOTE_scope.DBID;
                requestData.NOTE = NOTE_scope.NOTE;
                requestData.USER_ID = NOTE_scope.USER_ID;
                requestData.CREATED_AT = NOTE_scope.CREATED_AT;

                return requestData; /*|button_mapping|onbeforesend|7682433C-2955-6DCF-97E4-B3B6FB56A8D4||8587|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("NOTES_update")(requestData).then( /*|service_bookmark|bookmark|7682433C-2955-6DCF-97E4-B3B6FB56A8D4||2989|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|7682433C-2955-6DCF-97E4-B3B6FB56A8D4||7036|*/

                //$scope.upeatedAlert();
                Apperyio.navigateTo("NOTE_DETAILS", {
                    '_id': $scope.id
                });
                $scope.$apply();

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * user controller variables
         */
        $scope.NOTE = Apperyio.EntityAPI('NOTE');
        $scope.id = Apperyio.EntityAPI('String');
    }

});