define(['require', 'app'], function(require, APP) {

    /**
     * Controller for chartjs generated by Appery.io
     * @module chartjs
     */

    APP.controller('chartjs', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {

            $scope.ch();

        };

        /**
         * @function ch
         */
        $scope.ch = function() {
            var sessionToken = sessionStorage.getItem("sessionToken");
            console.log(sessionToken);
            $(document).ready(function() {
                $.ajax({
                    url: "	https://api.appery.io/rest/1/apiexpress/api/chart/LEAD_Chart/chart_lead?apiKey=0d0bbf5f-3256-451b-bac7-5b2341d8e7d3",
                    method: "GET",
                    headers: {

                        "x-appery-session-token": sessionToken,

                    },
                    success: function(data) {
                        console.log(data);
                        var STATUS = [];
                        var SCOUNT = [];

                        for (var i in data) {
                            STATUS.push("STATUS " + data[i].STATUS);
                            SCOUNT.push(data[i].SCOUNT);
                        }

                        var ctx = document.getElementById("myChart");
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: STATUS,
                                datasets: [{
                                    label: 'Remove Charts',
                                    data: SCOUNT,
                                    backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(54, 162, 235, 0.2)', 'rgba(255, 206, 86, 0.2)', 'rgba(75, 192, 192, 0.2)', 'rgba(153, 102, 255, 0.2)', 'rgba(255, 159, 64, 0.2)'],
                                    borderColor: ['rgba(255,99,132,1)', 'rgba(54, 162, 235, 1)', 'rgba(255, 206, 86, 1)', 'rgba(75, 192, 192, 1)', 'rgba(153, 102, 255, 1)', 'rgba(255, 159, 64, 1)'],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });

                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
            });

        };

        /**
         * user controller variables
         */
        $scope.data = Apperyio.EntityAPI('LEADS_STATUS');
        $scope.xys = Apperyio.EntityAPI('xys');
    }

});