define(['require', 'app'], function(require, APP) {

    /**
     * Controller for EVENT_LIST generated by Appery.io
     * @module EVENT_LIST
     */

    APP.controller('EVENT_LIST', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         * @param _lorc
         */
        $scope.init = function(_id, _lorc) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            $scope.LorC = $routeParams['_lorc'];
            $scope.showSpinner1 = true;
            $scope.$apply();

            var requestData = {};
            requestData = (function mapping8530($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('EVENTS2_find.request.data', undefined, true);

                var id_scope = $scope.id;
                var LorC_scope = $scope.LorC;
                requestData.where.COMPANY_DBID = id_scope;
                requestData.where.CLIENT_OR_LEAD = LorC_scope;

                console.log(id_scope + ' ***************************************** ' + LorC_scope);
                return requestData; /*|button_mapping|onbeforesend|666A5859-35E1-78C7-121C-4A21AE369434||8530|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("EVENTS2_find")(requestData).then( /*|service_bookmark|bookmark|666A5859-35E1-78C7-121C-4A21AE369434||3095|*/

            function(success) { // success callback
                (function mapping6049(success, $scope) {
                    console.log(success);
                    var EVENTS_scope = $scope.EVENTS;
                    EVENTS_scope = [];
                    for (var i = 0, l = success.length; i < l; i++) {
                        EVENTS_scope[i] = Apperyio.EntityAPI('Events.[i]');
                        EVENTS_scope[i] = success[i];
                        console.log("found one");
                    }

                    $scope.EVENTS = EVENTS_scope;

                    for (var event in EVENTS_scope)
                    $scope.companies.event.DBID = findCompany(event.COMPANY_DBID);
                    console.log("done founding1"); /*|button_mapping|onsuccess|666A5859-35E1-78C7-121C-4A21AE369434||6049|*/

                    $scope.showSpinner1 = false;
                    console.log("done founding2");
                    $scope.$apply();
                    console.log("done founding3");
                    console.log("success: " + $scope.EVENTS[0].DBID);
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function CREATE
         */
        $scope.CREATE = function() {
            console.log($scope.id);
            console.log($scope.LorC);
            Apperyio.navigateTo("EVENT_CREATE", {
                '_id': $scope.id,
                '_lorc': $scope.LorC
            });
        };

        /**
         * @function DETAILS
         * @param eventid
         */
        $scope.DETAILS = function(eventid) {
            Apperyio.navigateTo("EVENT_DETAILS", {
                '_id': eventid
            });
        };

        /**
         * @function findCompany
         * @param id
         * @param col
         */
        $scope.findCompany = function(id, col) {
            if (col === 'Lead') return $scope.findLead(id);
            else return $scope.findClient();
        };

        /**
         * @function findLead
         * @param id
         */
        $scope.findLead = function(id) {
            var requestData = {};
            requestData = (function mapping1361($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('LEAD2_get.request.data', undefined, true);

                var id_scope = id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|EB2C30CF-AC73-8640-265C-150BC85BA6EB||1361|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LEAD2_get")(requestData).then( /*|service_bookmark|bookmark|EB2C30CF-AC73-8640-265C-150BC85BA6EB||4598|*/

            function(success) { // success callback
                (function mapping5602(success, $scope) {
                    console.log(success.NAME);
                    return success.NAME; /*|button_mapping|onsuccess|EB2C30CF-AC73-8640-265C-150BC85BA6EB||5602|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function findClient
         * @param id
         */
        $scope.findClient = function(id) {
            var requestData = {};
            requestData = (function mapping5667($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_get.request.data', undefined, true);

                var id_scope = id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|36D74632-68E6-9F0B-9406-47450DF64FAA||5667|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_get")(requestData).then( /*|service_bookmark|bookmark|36D74632-68E6-9F0B-9406-47450DF64FAA||9395|*/

            function(success) { // success callback
                (function mapping1193(success, $scope) {
                    console.log(success.NAME);
                    return success.NAME; /*|button_mapping|onsuccess|36D74632-68E6-9F0B-9406-47450DF64FAA||1193|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.EVENTS = Apperyio.EntityAPI('Events');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.LorC = Apperyio.EntityAPI('String');
        $scope.companies = Apperyio.EntityAPI('Object');
    }

});