define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Contacts generated by Appery.io
     * @module Contacts
     */

    APP.controller('Contacts', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         * @param lorc
         */
        $scope.init = function(_id, lorc) {
            //On load screen logic
            console.log("landed here");
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            $scope.lorc = $routeParams['lorc'];
            $scope.showSpinner1 = true;
            $scope.$apply();

            var requestData = {};
            requestData = (function mapping8060($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_find.request.data', undefined, true);

                var id_scope = $scope.id;
                var lorc_scope = $scope.lorc;
                requestData.where.LEAD_DBID = id_scope;
                requestData.where.LEAD_OR_CLIENT = lorc_scope;

                return requestData; /*|button_mapping|onbeforesend|23FBC639-DB38-6690-3788-5BE14083EC02||8060|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_find")(requestData).then( /*|service_bookmark|bookmark|23FBC639-DB38-6690-3788-5BE14083EC02||8072|*/

            function(success) { // success callback
                (function mapping7452(success, $scope) {
                    var CONTACTS_scope = $scope.CONTACTS;
                    CONTACTS_scope = [];
                    for (var i = 0, l = success.length; i < l; i++) {
                        CONTACTS_scope[i] = Apperyio.EntityAPI('CONTACTS.[i]');
                        CONTACTS_scope[i] = success[i];
                        console.log("found one");
                    }

                    $scope.CONTACTS = CONTACTS_scope;
                    console.log("done founding1"); /*|button_mapping|onsuccess|23FBC639-DB38-6690-3788-5BE14083EC02||7452|*/

                    $scope.showSpinner1 = false;
                    console.log("done founding2");
                    $scope.$apply();
                    console.log("done founding3");
                    console.log("success: " + $scope.CONTACTS[0].FULLNAME);
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);

            }, function(notify) { // notify callback, can fire few times
                console.log(notify)
            });

        };

        /**
         * @function CREATE
         * @param lorc
         */
        $scope.CREATE = function(lorc) {
            Apperyio.navigateTo("CONTACT_CREATE", {
                '_id': $scope.id,
                'lorc': $scope.lorc
            });
        };

        /**
         * @function DETAILS
         * @param id2
         */
        $scope.DETAILS = function(id2) {
            console.log(id2);
            Apperyio.navigateTo("CONTACT_DETAILS", {
                '_id': id2
            });
        };

        /**
         * @function EDIT
         * @param id2
         */
        $scope.EDIT = function(id2) {
            Apperyio.navigateTo("CONTACT_EDIT", {
                '_id': id2
            });
        };

        /**
         * @function DELETE
         * @param id2
         */
        $scope.DELETE = function(id2) {
            var requestData = {};
            requestData = (function mapping5676($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_delete.request.data', undefined, true);

                var CONTACT_scope = $scope.CONTACT;
                requestData.DBID = id2;

                return requestData; /*|button_mapping|onbeforesend|39F56DAD-D3E3-3974-896B-59B9AB4232B1||5676|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_delete")(requestData).then( /*|service_bookmark|bookmark|39F56DAD-D3E3-3974-896B-59B9AB4232B1||8902|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|39F56DAD-D3E3-3974-896B-59B9AB4232B1||8506|*/

                //alert("Deleted");
                $scope.deletedAlert();
                $scope.init();

            }, function(error) { // callback to handle request error
                console.log(error);

            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function deleteConfirm
         * @param id2
         */
        $scope.deleteConfirm = function(id2) {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.DELETE(_id)();
            }

            navigator.notification.confirm('Are you sure you want to delete this?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Delete', // title
            ['Yes', 'No'] // buttonLabels
            );
        };

        /**
         * @function deletedAlert
         */
        $scope.deletedAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('This client has been deleted', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * user controller variables
         */
        $scope.showSpinner1 = Apperyio.EntityAPI('Boolean');
        $scope.CONTACTS = Apperyio.EntityAPI('CONTACTS');
        $scope.Token = Apperyio.EntityAPI('String');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.CONTACT = Apperyio.EntityAPI('CONTACT');
        $scope.lorc = Apperyio.EntityAPI('String');
    }

});