define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CONTACT_DETAILS generated by Appery.io
     * @module CONTACT_DETAILS
     */

    APP.controller('CONTACT_DETAILS', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            console.log($scope.id);

            var requestData = {};
            requestData = (function mapping5509($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|61E8F278-87AF-1B37-A307-138960AAC866||5509|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_get")(requestData).then( /*|service_bookmark|bookmark|61E8F278-87AF-1B37-A307-138960AAC866||6385|*/

            function(success) { // success callback
                (function mapping6604(success, $scope) {
                    var CONTACT_scope = $scope.CONTACT;
                    CONTACT_scope.STATUS = success.STATUS;
                    CONTACT_scope.PHONE_1 = success.PHONE_1;
                    CONTACT_scope.CITY = success.CITY;
                    CONTACT_scope.INDUSTRY = success.INDUSTRY;
                    CONTACT_scope.WEBSITE = success.WEBSITE;
                    CONTACT_scope.FULLNAME = success.FULLNAME;
                    CONTACT_scope.PHONE_2 = success.PHONE_2;
                    CONTACT_scope.COMPANY = success.COMPANY;
                    CONTACT_scope.REGION = success.REGION;
                    CONTACT_scope.DESCRIPTION = success.DESCRIPTION;
                    CONTACT_scope.TITLE = success.TITLE;
                    CONTACT_scope.ADDRESS = success.ADDRESS;
                    CONTACT_scope.TWITTER_ID = success.TWITTER_ID;
                    CONTACT_scope.MAIN_CONTACT = success.MAIN_CONTACT;
                    CONTACT_scope.FACEBOOK_ID = success.FACEBOOK_ID;
                    CONTACT_scope.INSTAGRAM_ID = success.INSTAGRAM_ID;
                    CONTACT_scope.NOTES = success.NOTES;
                    CONTACT_scope.E_MAIL = success.E_MAIL;
                    CONTACT_scope.DOB = success.DOB;
                    CONTACT_scope.OWNER = success.OWNER;
                    CONTACT_scope.SOURCE = success.SOURCE;
                    CONTACT_scope.LEAD_DBID = success.LEAD_DBID;
                    CONTACT_scope.HEADCOUNT = success.HEADCOUNT;
                    CONTACT_scope.COUNTRY = success.COUNTRY;
                    CONTACT_scope.RATING = success.RATING;
                    CONTACT_scope.LEAD_OR_CLIENT = success.LEAD_OR_CLIENT;
                    $scope.CONTACT = CONTACT_scope; /*|button_mapping|onsuccess|61E8F278-87AF-1B37-A307-138960AAC866||6604|*/

                    if ($scope.CONTACT.LEAD_OR_CLIENT === 'Lead') $scope.findLead();
                    else $scope.findClient();
                    console.log($scope.CONTACT);
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);

            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            Apperyio.navigateTo("CONTACT_EDIT", {
                '_id': $scope.id
            });
        };

        /**
         * @function DELETE
         */
        $scope.DELETE = function() {
            var requestData = {};
            requestData = (function mapping6586($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_delete.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|1ABA258E-DC8A-9030-344C-5A0CC0064CA8||6586|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_delete")(requestData).then( /*|service_bookmark|bookmark|1ABA258E-DC8A-9030-344C-5A0CC0064CA8||4686|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|1ABA258E-DC8A-9030-344C-5A0CC0064CA8||1146|*/

                console.log("success");
                //alert("Deleted");
                $scope.deleteAlert();
                Apperyio.navigateTo("Contacts");
                $scope.$apply();
            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function findLead
         */
        $scope.findLead = function() {
            var requestData = {};
            requestData = (function mapping8460($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('LEAD2_find.request.data', undefined, true);

                var CONTACT_scope = $scope.CONTACT;
                requestData.where.DBID = CONTACT_scope.LEAD_DBID;

                return requestData; /*|button_mapping|onbeforesend|0CB39F00-8F2F-2804-4F46-488C7832A36F||8460|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LEAD2_find")(requestData).then( /*|service_bookmark|bookmark|0CB39F00-8F2F-2804-4F46-488C7832A36F||1171|*/

            function(success) { // success callback
                (function mapping3265(success, $scope) {
                    var LEADS_scope = $scope.LEADS;
                    LEADS_scope = success;
                    $scope.LEADS = LEADS_scope; /*|button_mapping|onsuccess|0CB39F00-8F2F-2804-4F46-488C7832A36F||3265|*/

                    console.log("Lead name: " + $scope.LEADS[0].NAME);
                    $scope.leadname = $scope.LEADS[0].NAME;
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function confirmDelete
         */
        $scope.confirmDelete = function() {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.DELETE()();
            }

            navigator.notification.confirm('Are you sure you want to delete this?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Delete', // title
            ['Yes', 'No'] // buttonLabels
            );
        };

        /**
         * @function deletedAlert
         */
        $scope.deletedAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('Record has been deleted', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['Yes'] // buttonLabels
            );
        };

        /**
         * @function findClient
         */
        $scope.findClient = function() {
            var requestData = {};
            requestData = (function mapping1009($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_find.request.data', undefined, true);

                var CONTACT_scope = $scope.CONTACT;
                requestData.where.DBID = CONTACT_scope.LEAD_DBID;

                return requestData; /*|button_mapping|onbeforesend|CA81F38F-8077-E318-AE54-2FA9AEF8B183||1009|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_find")(requestData).then( /*|service_bookmark|bookmark|CA81F38F-8077-E318-AE54-2FA9AEF8B183||4611|*/

            function(success) { // success callback
                (function mapping9389(success, $scope) {
                    var leadname_scope = $scope.leadname;
                    leadname_scope = success[0].NAME;
                    $scope.leadname = leadname_scope; /*|button_mapping|onsuccess|CA81F38F-8077-E318-AE54-2FA9AEF8B183||9389|*/

                    console.log("Client name: " + $scope.CLIENTS[0].NAME);
                    $scope.leadname = $scope.CLIENTS[0].NAME;
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function NOTES
         */
        $scope.NOTES = function() {
            Apperyio.navigateTo("ATTACHED_NOTE_LIST", {
                '_id': $scope.id,
                'type': 'Contact'
            });
        };

        /**
         * user controller variables
         */
        $scope.id = Apperyio.EntityAPI('String');
        $scope.CONTACT = Apperyio.EntityAPI('CONTACT');
        $scope.LEADS = Apperyio.EntityAPI('LEADS');
        $scope.leadname = Apperyio.EntityAPI('String');
        $scope.CLIENTS = Apperyio.EntityAPI('CLIENTS');
    }

});