define(['require', 'app'], function(require, APP) {

    /**
     * Controller for LEAD_DETAILS_Oracle generated by Appery.io
     * @module LEAD_DETAILS_Oracle
     */

    APP.controller('LEAD_DETAILS_Oracle', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];

            console.log("start1");
            //On load screen logic
/*$scope.state = false;
var $routeParams = Apperyio.get("$routeParams");
$scope.id = $routeParams['_id'];*/
            //alert(ID);

            var requestData = {};
            requestData = (function mapping3194($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('LEAD2_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|175BF4BC-C65A-5402-F594-8EDBD2E055F9||3194|*/
            })($scope);
            console.log("start2");
            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LEAD2_get")(requestData).then( /*|service_bookmark|bookmark|175BF4BC-C65A-5402-F594-8EDBD2E055F9||8540|*/

            function(success) { // success callback
                (function mapping2137(success, $scope) {
                    var LEAD_scope = $scope.LEAD;
                    LEAD_scope = success;
                    $scope.LEAD = LEAD_scope; /*|button_mapping|onsuccess|175BF4BC-C65A-5402-F594-8EDBD2E055F9||2137|*/
                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);

            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function delete_details
         * @param _id
         */
        $scope.delete_details = function(_id) {
/*$scope.state = false;
var $routeParams = Apperyio.get("$routeParams");
$scope.id = $routeParams['_id'];*/

            var requestData = {};
            requestData = (function mapping8407($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('LEAD2_delete.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|8D6308C5-4F3C-6856-B7E9-36FF31A2C930||8407|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LEAD2_delete")(requestData).then( /*|service_bookmark|bookmark|8D6308C5-4F3C-6856-B7E9-36FF31A2C930||2068|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|8D6308C5-4F3C-6856-B7E9-36FF31A2C930||3711|*/
                console.log("success");
                //alert("Deleted");
                $scope.deleteAlert();
                Apperyio.navigateTo("LEAD_LIST_Oracle");
                $scope.$apply();

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function edit_details
         */
        $scope.edit_details = function() {
            //alert(_id);
            Apperyio.navigateTo("LEAD_EDIT_Oracle", {
                '_id': $scope.LEAD.DBID
            });
        };

        /**
         * @function success
         */
        $scope.success = function() {
            Apperyio.navigateTo("LEAD", {});

        };

        /**
         * @function confirmDelete
         * @param _id
         */
        $scope.confirmDelete = function(_id) {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.delete_details();
            }

            navigator.notification.confirm('Are you sure you want to delete this?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Delete', // title
            ['Submit', 'Cancle'] // buttonLabels
            );
        };

        /**
         * @function contacts
         * @param _id
         */
        $scope.contacts = function(_id) {
            Apperyio.navigateTo("Contacts", {
                '_id': _id,
                'lorc': 'Lead'
            });
        };

        /**
         * @function EVENTS
         * @param _id
         */
        $scope.EVENTS = function(_id) {
            Apperyio.navigateTo("EVENT_LIST", {
                '_id': _id,
                '_lorc': "Lead"
            });
        };

        /**
         * @function deleteAlert
         */
        $scope.deleteAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('This client has been deleted', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * @function NOTES
         */
        $scope.NOTES = function() {
            Apperyio.navigateTo("ATTACHED_NOTE_LIST", {
                '_id': $scope.id,
                'type': 'Lead'
            });
        };

        /**
         * user controller variables
         */
        $scope.LEAD = Apperyio.EntityAPI('LEAD');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.Lorc = Apperyio.EntityAPI('String');
    }

});