define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Calendar generated by Appery.io
     * @module Calendar
     */

    APP.controller('Calendar', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {

        };

        /**
         * user controller variables
         */
    }

});