define(['require', 'app'], function(require, APP) {

    /**
     * Controller for push_notifications generated by Appery.io
     * @module push_notifications
     */

    APP.controller('push_notifications', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * @function PushRegisterDevice
         */
        $scope.PushRegisterDevice = function() {
            console.log("start");
            var requestData = {}; /*|button_mapping|onbeforesend|F9F14408-BE14-8996-6A27-FF530AC170B2||4318|*/

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("PushRegisterDevice")(requestData).then( /*|service_bookmark|bookmark|F9F14408-BE14-8996-6A27-FF530AC170B2||5166|*/

            function(success) { // success callback
                (function mapping9556(success, $scope) {
                    var Push_scope = $scope.Push;
                    Push_scope.token = success.token;
                    Push_scope.deviceID = success.deviceID;
                    Push_scope.timeZone = success.timeZone;
                    Push_scope.type = success.type;
                    Push_scope._createdAt = success._createdAt;
                    Push_scope._updatedAt = success._updatedAt;
                    Push_scope._id = success._id;
                    $scope.Push = Push_scope; /*|button_mapping|onsuccess|F9F14408-BE14-8996-6A27-FF530AC170B2||9556|*/

                })(success, $scope);
                $scope.$apply();

                console.log($scope.Push);
                alert($scope.Push);
                $scope.$apply();
            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.Push = Apperyio.EntityAPI('Push');
    }

});