define(['require', 'app'], function(require, APP) {

    /**
     * Controller for NOTE_CREATE generated by Appery.io
     * @module NOTE_CREATE
     */

    APP.controller('NOTE_CREATE', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            //$scope.userid = sessionStorage.getItem("userid");
            $scope.userid = "57cc88a0e4b0ce1875dd5468";
            console.log($scope.userid);
        };

        /**
         * @function CREATE
         */
        $scope.CREATE = function() {
            var requestData = {};
            requestData = (function mapping4481($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('NOTES_create.request.data', undefined, true);

                var NOTE_scope = $scope.NOTE;
                var userid_scope = $scope.userid;
                requestData.NOTE = NOTE_scope.NOTE;
                requestData.USER_ID = userid_scope;

                return requestData; /*|button_mapping|onbeforesend|DB12CA0B-1BEB-D72E-CB59-41CF6675CF8A||4481|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("NOTES_create")(requestData).then( /*|service_bookmark|bookmark|DB12CA0B-1BEB-D72E-CB59-41CF6675CF8A||1066|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|DB12CA0B-1BEB-D72E-CB59-41CF6675CF8A||5946|*/

                console.log("create");
                Apperyio.navigateTo("NOTE_LIST");
                $scope.$apply();

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * user controller variables
         */
        $scope.NOTE = Apperyio.EntityAPI('NOTE');
        $scope.userid = Apperyio.EntityAPI('String');
    }

});