define(['require', 'app'], function(require, APP) {

    /**
     * Controller for mailgun generated by Appery.io
     * @module mailgun
     */

    APP.controller('mailgun', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            // On load screen logic
            $scope.email.from = "Excited User <user@enter-your-domain.mailgun.org>";
        };

        /**
         * @function sendEmail
         */
        $scope.sendEmail = function() {
            var requestData = {};
            requestData = (function mapping1383($scope) {
                var requestData = {};
                requestData.params = Apperyio.EntityAPI('MailgunEmail_Mailgun_service.request.query', undefined, true);

                var email_scope = $scope.email;
                requestData.params.to = email_scope.to;
                requestData.params.subject = email_scope.subject;
                requestData.params.text = email_scope.body;
                requestData.params.from = email_scope.from;

                return requestData; /*|button_mapping|onbeforesend|7E8BA6AA-1FCF-4815-B171-73CCDC1AAA04||1383|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("MailgunEmail_Mailgun_service")(requestData).then( /*|service_bookmark|bookmark|7E8BA6AA-1FCF-4815-B171-73CCDC1AAA04||1927|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|7E8BA6AA-1FCF-4815-B171-73CCDC1AAA04||9730|*/
                $scope.showAlert("Email sent. Thanks for using Appery.io + Mailgun.");
            }, function(error) { // callback to handle request error
                $scope.showAlert("Error sending email. Please check API settings.");

            }, function(notify) { // notify callback, can fire few times
            });
        };

        /**
         * @function showAlert
         * @param msg
         */
        $scope.showAlert = function(msg) {
            var $ionicPopup = Apperyio.get("$ionicPopup");
            var alertPopup = $ionicPopup.alert({
                title: 'Information',
                template: msg
            });
            alertPopup.then(function(res) {
                // you can do something here
            });
        };

        /**
         * user controller variables
         */
        $scope.email = Apperyio.EntityAPI('Email');
    }

});