define(['require', 'app'], function(require, APP) {

    /**
     * Controller for LEAD_CREATE_Oracle generated by Appery.io
     * @module LEAD_CREATE_Oracle
     */

    APP.controller('LEAD_CREATE_Oracle', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            $scope.userid = sessionStorage.getItem("userid");
            $scope.userid = "57cc88a0e4b0ce1875dd5468";
            console.log($scope.userid);
        };

        /**
         * @function CREATE
         */
        $scope.CREATE = function() {
            console.log("start");
            var requestData = {};
            requestData = (function mapping9392($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('LEAD2_create.request.data', undefined, true);

                var LEAD_scope = $scope.LEAD;
                requestData.STATUS = LEAD_scope.STATUS;
                requestData.NOTES = LEAD_scope.NOTES;
                requestData.E_MAIL = LEAD_scope.E_MAIL;
                requestData.COUNTRY = LEAD_scope.COUNTRY;
                requestData.REGION = LEAD_scope.REGION;
                requestData.HEADCOUNT = LEAD_scope.HEADCOUNT;
                requestData.USER_ID = $scope.userid;
                requestData.TWITTER_ID = LEAD_scope.TWITTER_ID;
                requestData.WEBSITE = LEAD_scope.WEBSITE;
                requestData.FACEBOOK_ID = LEAD_scope.FACEBOOK_ID;
                requestData.PHONE_2 = LEAD_scope.PHONE_2;
                requestData.INDUSTRY = LEAD_scope.INDUSTRY;
                requestData.ID = LEAD_scope.ID;
                requestData.ADDRESS = LEAD_scope.ADDRESS;
                requestData.ANN_REVENUE = LEAD_scope.ANN_REVENUE;
                requestData.INSTAGRAM_ID = LEAD_scope.INSTAGRAM_ID;
                requestData.DESCRIPTION = LEAD_scope.DESCRIPTION;
                requestData.CITY = LEAD_scope.CITY;
                requestData.STREET = LEAD_scope.STREET;
                requestData.NAME = LEAD_scope.NAME;
                requestData.PHONE_1 = LEAD_scope.PHONE_1;
                requestData.STATUS = LEAD_scope.STATUS;
                if (requestData.STATUS === "") requestData.STATUS = "Inactive";

                return requestData; /*|button_mapping|onbeforesend|BC42303F-0E1A-486D-3349-F6C923D879B9||9392|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            if (requestData.NAME) {
                Apperyio.get("LEAD2_create")(requestData).then( /*|service_bookmark|bookmark|BC42303F-0E1A-486D-3349-F6C923D879B9||7798|*/

                function(success) { // success callback
                    /*|button_mapping|onsuccess|BC42303F-0E1A-486D-3349-F6C923D879B9||6345|*/

                    if ($scope.LEAD.STATUS === "Contacted") {
                        $scope.addToClients();
                    }
                    console.log("create");
                    Apperyio.navigateTo("LEAD_LIST_Oracle");
                    $scope.$apply();
                }, function(error) { // callback to handle request error
                    console.log(error);

                }, function(notify) { // notify callback, can fire few times
                    console.log(notify);
                });
            } else {
                alert("You can't add a lead that has no name!");
            }

        };

        /**
         * @function find
         */
        $scope.find = function() {
            var requestData = {};
            requestData = (function mapping9385($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('LEAD2_find.request.data', undefined, true);

                var LEAD_scope = $scope.LEAD;
                requestData.where.NAME = LEAD_scope.NAME;

                return requestData; /*|button_mapping|onbeforesend|E86FC280-92E6-9EA9-F25E-B5E7FB98F6C9||9385|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LEAD2_find")(requestData).then( /*|service_bookmark|bookmark|E86FC280-92E6-9EA9-F25E-B5E7FB98F6C9||3940|*/

            function(success) { // success callback
                (function mapping9332(success, $scope) {
                    var LEADS_scope = $scope.LEADS;
                    LEADS_scope = [];
                    for (var i = 0, l = success.length; i < l; i++) {
                        LEADS_scope[i] = Apperyio.EntityAPI('LEADS.[i]');
                        LEADS_scope[i] = success[i];
                    }
                    $scope.LEADS = LEADS_scope;
                    console.log(success.length);

                    if (success.length === 0) {
                        console.log("Create");
                        $scope.CREATE();
                    } else {
                        console.log("Record already exists");

                    }

                    /*|button_mapping|onsuccess|E86FC280-92E6-9EA9-F25E-B5E7FB98F6C9||9332|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function addToClients
         */
        $scope.addToClients = function() {
            var requestData = {};
            requestData = (function mapping2248($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_create.request.data', undefined, true);

                var LEAD_scope = $scope.LEAD;
                requestData.STATUS = LEAD_scope.STATUS;
                requestData.NOTES = LEAD_scope.NOTES;
                requestData.COUNTRY = LEAD_scope.COUNTRY;
                requestData.HEADCOUNT = LEAD_scope.HEADCOUNT;
                requestData.USER_ID = LEAD_scope.USER_ID;
                requestData.TWITTER_ID = LEAD_scope.TWITTER_ID;
                requestData.WEBSITE = LEAD_scope.WEBSITE;
                requestData.PHONE_2 = LEAD_scope.PHONE_2;
                requestData.ADDRESS = LEAD_scope.ADDRESS;
                requestData.ANN_REVENUE = LEAD_scope.ANN_REVENUE;
                requestData.E_MAIL = LEAD_scope.E_MAIL;
                requestData.REGION = LEAD_scope.REGION;
                requestData.FACEBOOK_ID = LEAD_scope.FACEBOOK_ID;
                requestData.INDUSTRY = LEAD_scope.INDUSTRY;
                requestData.SOURCE = LEAD_scope.SOURCE;
                requestData.PHONE_1 = LEAD_scope.PHONE_1;
                requestData.CITY = LEAD_scope.CITY;
                requestData.INSTAGRAM_ID = LEAD_scope.INSTAGRAM_ID;
                requestData.DESCRIPTION = LEAD_scope.DESCRIPTION;
                requestData.NAME = LEAD_scope.NAME;

                return requestData; /*|button_mapping|onbeforesend|888088F3-1A05-3E05-55ED-9535994173F9||2248|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("CLIENT_create")(requestData).then( /*|service_bookmark|bookmark|888088F3-1A05-3E05-55ED-9535994173F9||2325|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|888088F3-1A05-3E05-55ED-9535994173F9||1125|*/

                Apperyio.navigateTo("CLIENT_LIST");
            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.LEAD = Apperyio.EntityAPI('LEAD');
        $scope.STATUS = Apperyio.EntityAPI('LEAD_STATUS');
        $scope.status = Apperyio.EntityAPI('String');
        $scope.LEADS = Apperyio.EntityAPI('LEADS');
        $scope.userid = Apperyio.EntityAPI('String');
    }

});