define(['require', 'app'], function(require, APP) {

    /**
     * Controller for menu generated by Appery.io
     * @module menu
     */

    APP.controller('menu', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            var sessionToken = sessionStorage.getItem("sessionToken");
            console.log(sessionToken);
        };

        /**
         * @function calendar
         */
        $scope.calendar = function() {

            var cal = window.plugins.calendar;
            var title = "New Years party";
            var loc = "The Club";
            var notes = "Bring pizza.";
            var start = new Date(2017, 0, 1, 20, 0, 0, 0, 0); // Jan 1st, 2015 20:00
            var end = new Date(2017, 0, 1, 22, 0, 0, 0, 0); // Jan 1st, 2015 22:00
            var calendarName = "MyCal";

            var success = function(message) {
                    alert("Success: " + JSON.stringify(message))
                };
            var error = function(message) {
                    alert("Error: " + message)
                };

            cal.createEventInteractively(title, loc, notes, start, end, onSuccess, onError);

            var options = cal.getCalendarOptions(); // grab the defaults
            options.firstReminderMinutes = 180; // default is 60, pass in null for no reminder
            options.secondReminderMinutes = 120;
            options.url = "https://www.telerik.com";
            options.calendar.calendarName = "MyCal"; // iOS only, created for you if not found
            options.calendarId = 1; // Android only, use id obtained from listCalendars()
            // recurrence options
            options.recurrence = "monthly"; // supported are: daily, weekly, monthly, yearly
            options.recurrenceEndDate = new Date(2016, 10, 1, 0, 0, 0, 0, 0); // leave empty to recur forever
            options.recurrenceInterval = 2; // once every 2 months in this case, default: 1
            // create the event
            cal.createEventWithOptions(title, loc, notes, start, end, options, success, error);

            // to open the calendar app at 'today'
            window.plugins.calendar.openCalendar();

        };

        /**
         * user controller variables
         */
        $scope.usert = Apperyio.EntityAPI('DataStorgage');
    }

});