define(['require', 'app'], function(require, APP) {

    /**
     * Controller for ATTACHED_NOTE_CREATE generated by Appery.io
     * @module ATTACHED_NOTE_CREATE
     */

    APP.controller('ATTACHED_NOTE_CREATE', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         * @param type
         */
        $scope.init = function(_id, type) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            $scope.type = $routeParams['type'];
        };

        /**
         * @function CREATE
         */
        $scope.CREATE = function() {
            var requestData = {};
            requestData = (function mapping5319($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('ATTACHED_NOTE_create.request.data', undefined, true);

                var NOTE_scope = $scope.NOTE;
                var type_scope = $scope.type;
                var id_scope = $scope.id;
                requestData.NOTE = NOTE_scope.NOTE;
                requestData.TYPE = type_scope;
                requestData.ATTACHMENT_ID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|C1163CC4-F82C-B24C-6B97-243E7AA89BD2||5319|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("ATTACHED_NOTE_create")(requestData).then( /*|service_bookmark|bookmark|C1163CC4-F82C-B24C-6B97-243E7AA89BD2||6921|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|C1163CC4-F82C-B24C-6B97-243E7AA89BD2||4029|*/

                console.log("create");
                Apperyio.navigateTo("ATTACHED_NOTE_LIST", {
                    '_id': $scope.id,
                    'type': $scope.type
                });
                $scope.$apply();

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * user controller variables
         */
        $scope.NOTE = Apperyio.EntityAPI('ATTACHED_NOTE');
        $scope.userid = Apperyio.EntityAPI('String');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.type = Apperyio.EntityAPI('String');
    }

});