define(['require', 'app'], function(require, APP) {

    /**
     * Controller for EVENT_EDIT generated by Appery.io
     * @module EVENT_EDIT
     */

    APP.controller('EVENT_EDIT', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * user controller variables
         */
    }

});