define(['require', 'app'], function(require, APP) {

    /**
     * Controller for ATTACHED_NOTE_DETAILS generated by Appery.io
     * @module ATTACHED_NOTE_DETAILS
     */

    APP.controller('ATTACHED_NOTE_DETAILS', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            console.log(_id);
            console.log($scope.id);

            console.log("start1");

            var requestData = {};
            requestData = (function mapping5706($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('ATTACHED_NOTE_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|AB74682A-9F7D-C5E6-632A-56DAFEFA449E||5706|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("ATTACHED_NOTE_get")(requestData).then( /*|service_bookmark|bookmark|AB74682A-9F7D-C5E6-632A-56DAFEFA449E||8562|*/

            function(success) { // success callback
                (function mapping9774(success, $scope) {
                    var NOTE_scope = $scope.NOTE;
                    NOTE_scope = success;
                    $scope.NOTE = NOTE_scope; /*|button_mapping|onsuccess|AB74682A-9F7D-C5E6-632A-56DAFEFA449E||9774|*/

                    if ($scope.NOTE.TYPE === 'Lead') {
                        requestData = {};
                        requestData = (function mapping3205($scope) {
                            var requestData = {};
                            requestData = Apperyio.EntityAPI('LEAD2_get.request.data', undefined, true);

                            var NOTE_scope = $scope.NOTE;
                            requestData.DBID = NOTE_scope.ATTACHMENT_ID;

                            return requestData; /*CLICK TO EDIT MAPPING*/
                        })($scope);

                        // read more about using rest services: https://links.appery.io/ve-snippet-rest
                        Apperyio.get("LEAD2_get")(requestData).then(

                        function(success) { // success callback
                            (function mapping5188(success, $scope) {
                                var a_name_scope = $scope.a_name;
                                a_name_scope = success.NAME;
                                $scope.a_name = a_name_scope; /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);

                        }, function(error) { // callback to handle request error
                        }, function(notify) { // notify callback, can fire few times
                        });

                    } else if ($scope.NOTE.TYPE === 'Client') {
                        requestData = {};
                        requestData = (function mapping2463($scope) {
                            var requestData = {};
                            requestData = Apperyio.EntityAPI('CLIENT_get.request.data', undefined, true);

                            var NOTE_scope = $scope.NOTE;
                            requestData.DBID = NOTE_scope.ATTACHMENT_ID;

                            return requestData; /*CLICK TO EDIT MAPPING*/
                        })($scope);

                        // read more about using rest services: https://links.appery.io/ve-snippet-rest
                        Apperyio.get("CLIENT_get")(requestData).then(

                        function(success) { // success callback
                            (function mapping1602(success, $scope) {
                                var a_name_scope = $scope.a_name;
                                a_name_scope = success.NAME;
                                $scope.a_name = a_name_scope; /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);

                        }, function(error) { // callback to handle request error
                        }, function(notify) { // notify callback, can fire few times
                        });

                    } else if ($scope.NOTE.TYPE === 'Contact') {
                        requestData = {};
                        requestData = (function mapping5347($scope) {
                            var requestData = {};
                            requestData = Apperyio.EntityAPI('CONTACT_get.request.data', undefined, true);

                            var NOTE_scope = $scope.NOTE;
                            requestData.DBID = NOTE_scope.ATTACHMENT_ID;

                            return requestData; /*CLICK TO EDIT MAPPING*/
                        })($scope);

                        // read more about using rest services: https://links.appery.io/ve-snippet-rest
                        Apperyio.get("CONTACT_get")(requestData).then(

                        function(success) { // success callback
                            (function mapping5964(success, $scope) {
                                var a_name_scope = $scope.a_name;
                                a_name_scope = success.FULLNAME;
                                $scope.a_name = a_name_scope; /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);

                        }, function(error) { // callback to handle request error
                        }, function(notify) { // notify callback, can fire few times
                        });

                    }

                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function DELETE
         */
        $scope.DELETE = function() {
            var requestData = {};
            requestData = (function mapping3051($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('ATTACHED_NOTE_delete.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|E94D41B7-BABC-19AB-9A08-699A4AFB4F9D||3051|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("ATTACHED_NOTE_delete")(requestData).then( /*|service_bookmark|bookmark|E94D41B7-BABC-19AB-9A08-699A4AFB4F9D||9758|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|E94D41B7-BABC-19AB-9A08-699A4AFB4F9D||8043|*/

                console.log("success");
                //alert("Deleted");
                //$scope.deleteAlert();
                Apperyio.navigateTo("ATTACHED_NOTE_LIST", {
                    '_id': $scope.NOTE.ATTACHMENT_ID,
                    'type': $scope.NOTE.TYPE
                });
                $scope.$apply();

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            Apperyio.navigateTo("ATTACHED_NOTE_EDIT", {
                '_id': $scope.id
            });
        };

        /**
         * user controller variables
         */
        $scope.NOTE = Apperyio.EntityAPI('ATTACHED_NOTE');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.a_id = Apperyio.EntityAPI('String');
        $scope.type = Apperyio.EntityAPI('String');
        $scope.a_name = Apperyio.EntityAPI('String');
    }

});