define(['require', 'app'], function(require, APP) {

    /**
     * Controller for NOTE_DETAILS generated by Appery.io
     * @module NOTE_DETAILS
     */

    APP.controller('NOTE_DETAILS', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            console.log(_id);
            console.log($scope.id);

            console.log("start1");

            var requestData = {};
            requestData = (function mapping5606($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('NOTES_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|B48168ED-9E65-3B90-131E-1AF318B051A2||5606|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("NOTES_get")(requestData).then( /*|service_bookmark|bookmark|B48168ED-9E65-3B90-131E-1AF318B051A2||5405|*/

            function(success) { // success callback
                (function mapping5495(success, $scope) {
                    var NOTE_scope = $scope.NOTE;
                    NOTE_scope.USER_ID = success.USER_ID;
                    NOTE_scope.DBID = success.DBID;
                    NOTE_scope.CREATED_AT = success.CREATED_AT;
                    NOTE_scope.NOTE = success.NOTE;
                    $scope.NOTE = NOTE_scope; /*|button_mapping|onsuccess|B48168ED-9E65-3B90-131E-1AF318B051A2||5495|*/

                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function DELETE
         */
        $scope.DELETE = function() {
            var requestData = {};
            requestData = (function mapping3103($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('NOTES_delete.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|FE732B04-FAF1-1619-3749-48AADF64EB0E||3103|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("NOTES_delete")(requestData).then( /*|service_bookmark|bookmark|FE732B04-FAF1-1619-3749-48AADF64EB0E||6848|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|FE732B04-FAF1-1619-3749-48AADF64EB0E||9727|*/

                console.log("success");
                //alert("Deleted");
                //$scope.deleteAlert();
                Apperyio.navigateTo("NOTE_LIST");
                $scope.$apply();

            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            Apperyio.navigateTo("NOTE_EDIT", {
                '_id': $scope.id
            });
        };

        /**
         * user controller variables
         */
        $scope.NOTE = Apperyio.EntityAPI('NOTE');
        $scope.id = Apperyio.EntityAPI('String');
    }

});