define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Welcome generated by Appery.io
     * @module Welcome
     */

    APP.controller('Welcome', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            var userData = Apperyio.get("dataStorage");
            $scope.user = userData.current;

        };

        /**
         * user controller variables
         */
        $scope.username = Apperyio.EntityAPI('String');
        $scope.email = Apperyio.EntityAPI('String');
        $scope.user = Apperyio.EntityAPI('User');
    }

});