define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CONTACT_EDIT generated by Appery.io
     * @module CONTACT_EDIT
     */

    APP.controller('CONTACT_EDIT', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            console.log($scope.id);

            var requestData = {};
            requestData = (function mapping6880($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|A41E879F-F02B-75CD-53E8-14AE93B6A318||6880|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_get")(requestData).then( /*|service_bookmark|bookmark|A41E879F-F02B-75CD-53E8-14AE93B6A318||9387|*/

            function(success) { // success callback
                (function mapping1456(success, $scope) {
                    var CONTACT_scope = $scope.CONTACT;
                    CONTACT_scope = success;
                    $scope.CONTACT = CONTACT_scope; /*|button_mapping|onsuccess|A41E879F-F02B-75CD-53E8-14AE93B6A318||1456|*/
                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function FIND
         */
        $scope.FIND = function() {
            var requestData = {};
            requestData = (function mapping5082($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_find.request.data', undefined, true);

                var CONTACT_scope = $scope.CONTACT;
                requestData.where.E_MAIL = CONTACT_scope.E_MAIL;

                return requestData; /*|button_mapping|onbeforesend|725A03DA-6B25-905C-C9E8-689788BF9A1C||5082|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_find")(requestData).then( /*|service_bookmark|bookmark|725A03DA-6B25-905C-C9E8-689788BF9A1C||5765|*/

            function(success) { // success callback
                (function mapping1351(success, $scope) {
                    var CONTACTS_scope = $scope.CONTACTS;
                    CONTACTS_scope = success;
                    $scope.CONTACTS = CONTACTS_scope; /*|button_mapping|onsuccess|725A03DA-6B25-905C-C9E8-689788BF9A1C||1351|*/

                    console.log("start looping");
                    for (var i = 0; i < $scope.CONTACTS.length; i++) {
                        console.log($scope.CONTACT.DBID);
                        console.log($scope.CONTACTS[i].DBID);
                        if ($scope.CONTACTS[i].DBID != $scope.CONTACT.DBID) {
                            //alert("You have entered aN E-mail of another contact... Please try entering a different E-mail");
                            $scope.recordExists();
                            console.log("exists");
                            return;
                        }
                    }
                    console.log("Edit");
                    $scope.EDIT();
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            var requestData = {};
            requestData = (function mapping5210($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CONTACT_update.request.data', undefined, true);

                var CONTACT_scope = $scope.CONTACT;
                requestData.STATUS = CONTACT_scope.STATUS;
                requestData.SOURCE = CONTACT_scope.SOURCE;
                requestData.FULLNAME = CONTACT_scope.FULLNAME;
                requestData.INDUSTRY = CONTACT_scope.INDUSTRY;
                requestData.WEBSITE = CONTACT_scope.WEBSITE;
                requestData.PHONE_1 = CONTACT_scope.PHONE_1;
                requestData.PHONE_2 = CONTACT_scope.PHONE_2;
                requestData.E_MAIL = CONTACT_scope.E_MAIL;
                requestData.REGION = CONTACT_scope.REGION;
                requestData.CITY = CONTACT_scope.CITY;
                requestData.TITLE = CONTACT_scope.TITLE;
                requestData.LEAD_OR_CLIENT = CONTACT_scope.LEAD_OR_CLIENT;
                requestData.MAIN_CONTACT = CONTACT_scope.MAIN_CONTACT;
                requestData.USER_ID = CONTACT_scope.USER_ID;
                requestData.FACEBOOK_ID = CONTACT_scope.FACEBOOK_ID;
                requestData.INSTAGRAM_ID = CONTACT_scope.INSTAGRAM_ID;
                requestData.TWITTER_ID = CONTACT_scope.TWITTER_ID;
                requestData.DOB = CONTACT_scope.DOB;
                requestData.COUNTRY = CONTACT_scope.COUNTRY;
                requestData.HEADCOUNT = CONTACT_scope.HEADCOUNT;
                requestData.OWNER = CONTACT_scope.OWNER;
                requestData.LEAD_DBID = CONTACT_scope.LEAD_DBID;
                requestData.ADDRESS = CONTACT_scope.ADDRESS;
                requestData.NOTES = CONTACT_scope.NOTES;
                requestData.DESCRIPTION = CONTACT_scope.DESCRIPTION;
                requestData.RATING = CONTACT_scope.RATING;
                requestData.ACCOUNT_DBID = CONTACT_scope.ACCOUNT_DBID;
                requestData.DBID = CONTACT_scope.DBID;

                return requestData; /*|button_mapping|onbeforesend|626E89B5-4A4C-E14C-1B3D-20F45F4690D9||5210|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CONTACT_update")(requestData).then( /*|service_bookmark|bookmark|626E89B5-4A4C-E14C-1B3D-20F45F4690D9||3429|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|626E89B5-4A4C-E14C-1B3D-20F45F4690D9||3130|*/

                //alert("Updated");
                //$scope.editAlert();
                console.log("Edited");
                Apperyio.navigateTo("CONTACT_DETAILS", {
                    '_id': $scope.id
                });
                $scope.$apply();

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function editConfirm
         */
        $scope.editConfirm = function() {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.FIND()();
            }

            navigator.notification.confirm('Are you sure you want to submit updates?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Update', // title
            ['Yes', 'No'] // buttonLabels
            );
        };

        /**
         * @function recordExists
         */
        $scope.recordExists = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('You have entered a name of another contact... Please try entering a different E-mail', // message
            onConfirm, // callback to invoke with index of button pressed
            'Sorry', // title
            ['OK'] // buttonLabels
            );

        };

        /**
         * @function editAlert
         */
        $scope.editAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('Record has bee updated', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['Yes'] // buttonLabels
            );
        };

        /**
         * user controller variables
         */
        $scope.CONTACT = Apperyio.EntityAPI('CONTACT');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.CONTACTS = Apperyio.EntityAPI('CONTACTS');
    }

});