define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CSS_Calendar generated by Appery.io
     * @module CSS_Calendar
     */

    APP.controller('CSS_Calendar', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            var d = new Date();

            var month = new Array();
            month[0] = "January";
            month[1] = "February";
            month[2] = "March";
            month[3] = "April";
            month[4] = "May";
            month[5] = "June";
            month[6] = "July";
            month[7] = "August";
            month[8] = "September";
            month[9] = "October";
            month[10] = "November";
            month[11] = "December";
            var monthname = month[d.getMonth()];

            $scope.Year.month = monthname;
            $scope.Year.Year = d.getFullYear();
            $scope.Year.day = d.getDate();
        };

        /**
         * @function setmonth
         */
        $scope.setmonth = function() {
            $scope.Year.month = "August";
        };

        /**
         * user controller variables
         */
        $scope.Year = Apperyio.EntityAPI('Year');
    }

});