define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Login_clone_1 generated by Appery.io
     * @module Login_clone_1
     */

    APP.controller('Login_clone_1', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * @function login
         */
        $scope.login = function() {
            console.log("start login")
            $scope.showSpinner2 = true;
            $scope.$apply();
            var requestData = {};
            requestData = (function mapping1795($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('AppClientLogin.request.data', undefined, true);

                var user_scope = $scope.user;
                requestData.username = user_scope.username;
                requestData.password = user_scope.password;

                return requestData; /*|button_mapping|onbeforesend|C61908AB-45BF-C81F-B091-C67AFE7FBC5F||1795|*/

                console.log("END AppClientLogin.request.data")
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("AppClientLogin")(requestData).then( /*|service_bookmark|bookmark|C61908AB-45BF-C81F-B091-C67AFE7FBC5F||8367|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|C61908AB-45BF-C81F-B091-C67AFE7FBC5F||6351|*/

                console.log(success);
                console.log("AppClientLogin")
                console.log(success[0].userName);

                $scope.$apply();

                var requestData = {};
                requestData = (function mapping1651($scope) {
                    var requestData = {};
                    requestData.data = Apperyio.EntityAPI('Obtain_Session_token_Service.request.body', undefined, true);

                    var user_scope = $scope.user;
                    requestData.data.username = user_scope.username;
                    requestData.data.password = user_scope.password;

                    return requestData; /*|button_mapping|onbeforesend|D60CC387-124C-C4DC-7CFB-1BCBB55038AB||1651|*/

                    console.log("Obtain_Session_token_Service.request.body")
                })($scope);

                // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
                Apperyio.get("Obtain_Session_token_Service")(requestData).then( /*|service_bookmark|bookmark|D60CC387-124C-C4DC-7CFB-1BCBB55038AB||6645|*/

                function(success) { // success callback
                    (function mapping2338(success, $scope) {
                        var user_scope = $scope.user;
                        user_scope.sessionToken = success.data.sessionToken;
                        $scope.user = user_scope;
                        console.log($scope.user.sessionToken);
                        sessionStorage.setItem("sessionToken", $scope.user.sessionToken);
                        var sessionToken = sessionStorage.getItem("sessionToken");
                        console.log(sessionToken); /*|button_mapping|onsuccess|D60CC387-124C-C4DC-7CFB-1BCBB55038AB||2338|*/

                        console.log("Obtain_Session_token_Service")
                    })(success, $scope);

                    var requestData = {};
                    requestData = (function mapping5655($scope) {
                        var requestData = {};
                        requestData.headers = Apperyio.EntityAPI('get_user_id_Service.request.headers', undefined, true);
                        requestData.params = Apperyio.EntityAPI('get_user_id_Service.request.query', undefined, true);
                        var sessionToken = sessionStorage.getItem("sessionToken");
                        console.log(sessionToken);
                        var user_scope = $scope.user;
                        requestData.headers['X-Appery-Session-Token'] = sessionToken;
                        requestData.params.where = {
                            'username': $scope.user.username
                        };

                        return requestData; /*CLICK TO EDIT MAPPING*/
                    })($scope);

                    // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
                    Apperyio.get("get_user_id_Service")(requestData).then(

                    function(success) { // success callback
                        (function mapping8055(success, $scope) {
                            var userid_scope = $scope.userid;
                            userid_scope = success.data[0]._id;
                            $scope.userid = userid_scope;
                            console.log($scope.userid);
                            sessionStorage.setItem("userid", $scope.userid);
                            var userid = sessionStorage.getItem("userid");
                            console.log(userid);

                            /*CLICK TO EDIT MAPPING*/
                        })(success, $scope);

                    }, function(error) { // callback to handle request error
                        console.log(error);

                    }, function(notify) { // notify callback, can fire few times
                        console.log(notify);
                    });
                }, function(error) { // callback to handle request error
                    console.log(error);

                }, function(notify) { // notify callback, can fire few times
                    console.log(notify);
                });

                $scope.showSpinner2 = false;
                Apperyio.navigateTo("menu", {});
                $scope.$apply();

            }, function(error) { // callback to handle request error
                //alert(error);
                console.log(error);
                //alert("Incorrect username or password");
                $scope.notloged();
                $scope.showSpinner2 = false;
                $scope.$apply();

            }, function(notify) { // notify callback, can fire few times
                //alert(notify);
                console.log(notify);
                $scope.showSpinner2 = false;
                $scope.$apply();
            });

            //$scope.APPlogin();

/*Apperyio.User.setDefaultDB('57cc7ddce4b037a0e24b24e0');

Apperyio.User.login({
    "username": $scope.user.username,
    "password": $scope.user.password
}).then(function(result) {
    console.log("loginsuccess_" + JSON.stringify(result));
}, function(error) {
    console.log("error_" + JSON.stringify(error));
});*/

/*
var requestData = {};
requestData = (function mapping4383($scope) {
    var requestData = {};
    requestData.params = Apperyio.EntityAPI('LoginUser_service.request.query', undefined, true);

    var user_scope = $scope.user;
    requestData.params.username = user_scope.username;
    requestData.params.password = user_scope.password;

    return requestData;
    /*|button_mapping|onbeforesend|3897C66E-BA08-47BC-954E-94F6450F3A10||4383|*/
            //})($scope);
            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            //Apperyio.get("LoginUser_service")(requestData).then( /*|service_bookmark|bookmark|3897C66E-BA08-47BC-954E-94F6450F3A10||1044|*/
            //  function(success) { // success callback
            /*|button_mapping|onsuccess|3897C66E-BA08-47BC-954E-94F6450F3A10||2693|*/
            // $scope.APPlogin();
            //test
            //var userData = Apperyio.get("dataStorage");
            //     userData.current = success.data;
            //},
            //function(error) { // callback to handle request error
            // alert("Incorrect username or password"); alert("Incorrect username or password");
/*window.plugins.toast.showWithOptions({
            message: 'Please try again!',
            duration: 'short',
            position: 'top'
        },
        function(a) {
            console.log('toast success: ' + a);
        },
        function(b) {
            alert('toast error: ' + b);
        });*/

            //window.plugins.toast.show('hi there','long','top');

/*var modalOptions = { // About Ionic Modal: https://devcenter.appery.io/documentation/angularjs/screens/#Modal_screen
            animation: 'slide-in-up', // The animation to show & hide with
            focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
            backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
            hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
        };

        Apperyio.get('Modals').loadModal("MessagePopup").then(
            function(modalInstance) {
                modalInstance.open(modalOptions).then(function(modal) {
                    modal.scope.modal = modal;
                    modal.show();
                });
            },
            function(error) {
                console.log(error);
            });*/

            //    },
            //  function(notify) { // notify callback, can fire few times
            //});

        };

        /**
         * @function test
         */
        $scope.test = function() {
/*alert("log");
 window.plugins.toast.showWithOptions(
    {
      message: "hey there",
      duration: "short", // which is 2000 ms. "long" is 4000. Or specify the nr of ms yourself.
      position: "bottom",
      addPixelsY: -40  // added a negative value to move it up a bit (default 0)
    },
    onSuccess, // optional
    onError    // optional
    
  );*/

            function onConfirm(buttonIndex) {
                alert('You selected button ' + buttonIndex);
/*if(buttonIndex === 1)
    Apperyio.navigateTo("LEAD_EDIT_Oracle", {});*/

            }

            navigator.notification.confirm('You are the winner!', // message
            onConfirm, // callback to invoke with index of button pressed
            'Game Over', // title
            ['Restart', 'Exit'] // buttonLabels
            );

        };

        /**
         * @function APPlogin
         */
        $scope.APPlogin = function() {

            console.log("start **************************************");

            var requestData = {};
            requestData = (function mapping8635($scope) {
                var requestData = {};
                requestData.params = Apperyio.EntityAPI('LoginUser_LoginUser1474303486448_service.request.query', undefined, true);

                var user_scope = $scope.user;
                requestData.params.username = user_scope.username;
                requestData.params.password = user_scope.password;

                console.log("start2 ************************************");
                return requestData; /*|button_mapping|onbeforesend|ED550DA4-B3C9-BF43-EAFE-53AB509CC015||8635|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LoginUser_LoginUser1474303486448_service")(requestData).then( /*|service_bookmark|bookmark|ED550DA4-B3C9-BF43-EAFE-53AB509CC015||4190|*/

            function(success) { // success callback
                (function mapping3903(success, $scope) {
                    console.log("start4 **************************************");

                    var user_scope = $scope.user;
                    user_scope.sessionToken = success.data.session;
                    $scope.user = user_scope; /*|button_mapping|onsuccess|ED550DA4-B3C9-BF43-EAFE-53AB509CC015||3903|*/
                    console.log("**************************" + $scope.user.sessionToken);
                    console.log("**************************" + $scope.user.sessionToken);

                    var requestData = {}; /*|button_mapping|onbeforesend|35BFA596-8A3C-1B72-0BBE-F3BFD984243F||2456|*/

                    // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
                    Apperyio.get("AppClientLogin")(requestData).then( /*|service_bookmark|bookmark|35BFA596-8A3C-1B72-0BBE-F3BFD984243F||6908|*/

                    function(success) { // success callback
                        /*|button_mapping|onsuccess|35BFA596-8A3C-1B72-0BBE-F3BFD984243F||8804|*/

                    }, function(error) { // callback to handle request error

                    }, function(notify) { // notify callback, can fire few times
                    });

                    var userData = Apperyio.get("dataStorage");
                    userData.current = success.data;
                    Apperyio.navigateTo("menu", {});
                    $scope.showSpinner2 = false;
                    console.log("********************" + $scope.user);
                })(success, $scope);
                //console.log("loginAPP");
                $scope.$apply();

            }, function(error) { // callback to handle request error
                alert("Incorrect username or password");
                console.log("error : ********************************* " + error);
                //$scope.showAlert("Incorrect username or password");

            }, function(notify) { // notify callback, can fire few times
            });
        };

        /**
         * @function changeLanguage
         * @param languageCode
         */
        $scope.changeLanguage = function(languageCode) {
            var $translate = Apperyio.get('$translate');
            $translate.use(languageCode);
            if (languageCode === 'ar') {

                $scope.languageCode = 'rtl';
            }
            if (languageCode === 'en') {
                $scope.languageCode = 'ltr';
            }
            $scope.$apply();

        };

        /**
         * @function showAlert
         * @param msg
         */
        $scope.showAlert = function(msg) {
            var $ionicPopup = Apperyio.get("$ionicPopup");
            var alertPopup = $ionicPopup.alert({
                title: 'Information',
                template: msg
            });
            alertPopup.then(function(res) {
                // you can do something here
            });

            $scope.showSpinner2 = false;
            $scope.$apply();
        };

        /**
         * @function notloged
         */
        $scope.notloged = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('Incorrect username or password', // message
            onConfirm, // callback to invoke with index of button pressed
            'Sorry', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * @function logint
         */
        $scope.logint = function() {
            var requestData = {};
            requestData = (function mapping5954($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('AppClientLogin.request.data', undefined, true);

                var user_scope = $scope.user;
                requestData.username = user_scope.username;
                requestData.password = user_scope.password;

                return requestData; /*|button_mapping|onbeforesend|84088ED6-FC9B-E07C-2DFF-337F2EA25A4E||5954|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("AppClientLogin")(requestData).then( /*|service_bookmark|bookmark|84088ED6-FC9B-E07C-2DFF-337F2EA25A4E||5730|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|84088ED6-FC9B-E07C-2DFF-337F2EA25A4E||3589|*/
                $scope.$apply();

                Apperyio.navigateTo("menu", {});
                $scope.$apply();
            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.user = Apperyio.EntityAPI('User');
        $scope.language = Apperyio.EntityAPI('DataStorgage');
        $scope.showSpinner2 = Apperyio.EntityAPI('Boolean');
        $scope.languageCode = Apperyio.EntityAPI('String');
        $scope.usert = Apperyio.EntityAPI('DataStorgage');
        $scope.userName = Apperyio.EntityAPI('String');
        $scope.userid = Apperyio.EntityAPI('String');
    }

});