define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CLIENT_CREATE generated by Appery.io
     * @module CLIENT_CREATE
     */

    APP.controller('CLIENT_CREATE', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            //$scope.userid = sessionStorage.getItem("userid");
            $scope.userid = "57cc88a0e4b0ce1875dd5468";
            console.log($scope.userid);
        };

        /**
         * @function FIND
         */
        $scope.FIND = function() {
            var requestData = {};
            requestData = (function mapping2337($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_find.request.data', undefined, true);

                var CLIENT_scope = $scope.CLIENT;
                requestData.where.NAME = CLIENT_scope.NAME;

                return requestData; /*|button_mapping|onbeforesend|8F3D4029-088C-6DA0-D2AE-F2B36B0C092D||2337|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_find")(requestData).then( /*|service_bookmark|bookmark|8F3D4029-088C-6DA0-D2AE-F2B36B0C092D||7517|*/

            function(success) { // success callback
                (function mapping5838(success, $scope) {
                    var CLIENTS_scope = $scope.CLIENTS;

                    CLIENTS_scope = [];
                    for (var i = 0, l = success.length; i < l; i++) {
                        CLIENTS_scope[i] = Apperyio.EntityAPI('CLIENTS.[i]');
                        CLIENTS_scope[i] = success[i];
                    }
                    $scope.CLIENTS = CLIENTS_scope;
                    console.log(success.length);

                    if (success.length === 0) {
                        console.log("Create");
                        $scope.CREATE();
                    } else {
                        $scope.recordExists();

                    } /*|button_mapping|onsuccess|8F3D4029-088C-6DA0-D2AE-F2B36B0C092D||5838|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function CREATE
         */
        $scope.CREATE = function() {
            var requestData = {};
            requestData = (function mapping4621($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_create.request.data', undefined, true);

                var CLIENT_scope = $scope.CLIENT;
                requestData.NAME = CLIENT_scope.NAME;
                requestData.DESCRIPTION = CLIENT_scope.DESCRIPTION;
                requestData.STATUS = CLIENT_scope.STATUS;
                requestData.INDUSTRY = CLIENT_scope.INDUSTRY;
                requestData.WEBSITE = CLIENT_scope.WEBSITE;
                requestData.PHONE_1 = CLIENT_scope.PHONE_1;
                requestData.PHONE_2 = CLIENT_scope.PHONE_2;
                requestData.E_MAIL = CLIENT_scope.E_MAIL;
                requestData.ADDRESS = CLIENT_scope.ADDRESS;
                requestData.REGION = CLIENT_scope.REGION;
                requestData.CITY = CLIENT_scope.CITY;
                requestData.COUNTRY = CLIENT_scope.COUNTRY;
                requestData.HEADCOUNT = CLIENT_scope.HEADCOUNT;
                requestData.SOURCE = CLIENT_scope.SOURCE;
                requestData.INSTAGRAM_ID = CLIENT_scope.INSTAGRAM_ID;
                requestData.USER_ID = $scope.userid;
                requestData.RATING = CLIENT_scope.RATING;
                requestData.TWITTER_ID = CLIENT_scope.TWITTER_ID;
                requestData.FACEBOOK_ID = CLIENT_scope.FACEBOOK_ID;
                requestData.ANN_REVENUE = CLIENT_scope.ANN_REVENUE;
                requestData.NOTES = CLIENT_scope.NOTES;

                if (requestData.STATUS === "") requestData.STATUS = "Not Contacted";

                return requestData; /*|button_mapping|onbeforesend|E3E6FF71-D978-44FE-BE30-6B9F2C291FB1||4621|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_create")(requestData).then( /*|service_bookmark|bookmark|E3E6FF71-D978-44FE-BE30-6B9F2C291FB1||2406|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|E3E6FF71-D978-44FE-BE30-6B9F2C291FB1||4627|*/

                console.log("create");
                Apperyio.navigateTo("CLIENT_LIST");
                $scope.$apply();
            }, function(error) { // callback to handle request error
                console.log(error);
            }, function(notify) { // notify callback, can fire few times
                console.log(notify);
            });

        };

        /**
         * @function recordExists
         */
        $scope.recordExists = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('There is a record already exists with this name', // message
            onConfirm, // callback to invoke with index of button pressed
            'Sorry', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * user controller variables
         */
        $scope.CLIENT = Apperyio.EntityAPI('CLIENT');
        $scope.CLIENTS = Apperyio.EntityAPI('CLIENTS');
        $scope.userid = Apperyio.EntityAPI('String');
    }

});