define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CLIENT_LIST generated by Appery.io
     * @module CLIENT_LIST
     */

    APP.controller('CLIENT_LIST', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            $scope.userid = sessionStorage.getItem("userid");
            $scope.userid = "57cc88a0e4b0ce1875dd5468";
            console.log($scope.userid);

            $scope.showSpinner1 = true;
            $scope.$apply();

            var requestData = {};
            requestData = (function mapping4203($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_find.request.data', undefined, true);

                var userid_scope = $scope.userid;
                requestData.where.USER_ID = userid_scope;

                return requestData; /*|button_mapping|onbeforesend|FD92C476-C87C-2E73-4D36-CCFAB6EC0DB2||4203|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_find")(requestData).then( /*|service_bookmark|bookmark|FD92C476-C87C-2E73-4D36-CCFAB6EC0DB2||5613|*/

            function(success) { // success callback
                (function mapping9628(success, $scope) {
                    var CLIENTS_scope = $scope.CLIENTS;
                    LEADS_scope = [];
                    for (var i = 0, l = success.length; i < l; i++) {
                        CLIENTS_scope[i] = Apperyio.EntityAPI('CLIENTS.[i]');
                        CLIENTS_scope[i] = success[i];
                    }
                    $scope.CLIENTS = CLIENTS_scope; /*|button_mapping|onsuccess|FD92C476-C87C-2E73-4D36-CCFAB6EC0DB2||9628|*/
                    $scope.showSpinner1 = false;
                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function EDIT
         * @param _id
         */
        $scope.EDIT = function(_id) {
            Apperyio.navigateTo("CLIENT_EDIT", {
                '_id': _id
            });
        };

        /**
         * @function DETAILS
         * @param _id
         */
        $scope.DETAILS = function(_id) {
            Apperyio.navigateTo("CLIENT_DETAILS", {
                '_id': _id
            });
        };

        /**
         * @function DELETE
         * @param _id
         */
        $scope.DELETE = function(_id) {
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = _id;

            var requestData = {};
            requestData = (function mapping4127($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_delete.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|46ECB0F4-2439-9B4A-999D-4CC979E3BABE||4127|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_delete")(requestData).then( /*|service_bookmark|bookmark|46ECB0F4-2439-9B4A-999D-4CC979E3BABE||8315|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|46ECB0F4-2439-9B4A-999D-4CC979E3BABE||9476|*/

                //$scope.deleteCofirmed();
                //alert("Deleted");
                $scope.deletedAlert();
                //Apperyio.navigateTo("LEAD_LIST_Oracle");
                $scope.init();
            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function confirmDelete
         * @param _id
         */
        $scope.confirmDelete = function(_id) {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.DELETE(_id)();
            }

            navigator.notification.confirm('Are you sure you want to delete this?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Delete', // title
            ['Yes', 'No'] // buttonLabels
            );
        };

        /**
         * @function deletedAlert
         */
        $scope.deletedAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('This client has been deleted', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * user controller variables
         */
        $scope.CLIENTS = Apperyio.EntityAPI('CLIENTS');
        $scope.TOKEN = Apperyio.EntityAPI('String');
        $scope.id = Apperyio.EntityAPI('String');
        $scope.showSpinner1 = Apperyio.EntityAPI('Boolean');
        $scope.userid = Apperyio.EntityAPI('String');
    }

});