define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Login generated by Appery.io
     * @module Login
     */

    APP.controller('Login', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * @function test
         */
        $scope.test = function() {
/*alert("log");
 window.plugins.toast.showWithOptions(
    {
      message: "hey there",
      duration: "short", // which is 2000 ms. "long" is 4000. Or specify the nr of ms yourself.
      position: "bottom",
      addPixelsY: -40  // added a negative value to move it up a bit (default 0)
    },
    onSuccess, // optional
    onError    // optional
    
  );*/

            function onConfirm(buttonIndex) {
                alert('You selected button ' + buttonIndex);
/*if(buttonIndex === 1)
    Apperyio.navigateTo("LEAD_EDIT_Oracle", {});*/

            }

            navigator.notification.confirm('You are the winner!', // message
            onConfirm, // callback to invoke with index of button pressed
            'Game Over', // title
            ['Restart', 'Exit'] // buttonLabels
            );

        };

        /**
         * @function APPlogin
         */
        $scope.APPlogin = function() {

            console.log("start **************************************");

            var requestData = {};
            requestData = (function mapping8635($scope) {
                var requestData = {};
                requestData.params = Apperyio.EntityAPI('LoginUser_LoginUser1474303486448_service.request.query', undefined, true);

                var user_scope = $scope.user;
                requestData.params.username = user_scope.username;
                requestData.params.password = user_scope.password;

                console.log("start2 ************************************");
                return requestData; /*|button_mapping|onbeforesend|ED550DA4-B3C9-BF43-EAFE-53AB509CC015||8635|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("LoginUser_LoginUser1474303486448_service")(requestData).then( /*|service_bookmark|bookmark|ED550DA4-B3C9-BF43-EAFE-53AB509CC015||4190|*/

            function(success) { // success callback
                (function mapping3903(success, $scope) {
                    console.log("start4 **************************************");

                    var user_scope = $scope.user;
                    user_scope.sessionToken = success.data.session;
                    $scope.user = user_scope; /*|button_mapping|onsuccess|ED550DA4-B3C9-BF43-EAFE-53AB509CC015||3903|*/
                    console.log("**************************" + $scope.user.sessionToken);
                    console.log("**************************" + $scope.user.sessionToken);

                    var requestData = {}; /*|button_mapping|onbeforesend|35BFA596-8A3C-1B72-0BBE-F3BFD984243F||2456|*/

                    // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
                    Apperyio.get("AppClientLogin")(requestData).then( /*|service_bookmark|bookmark|35BFA596-8A3C-1B72-0BBE-F3BFD984243F||6908|*/

                    function(success) { // success callback
                        /*|button_mapping|onsuccess|35BFA596-8A3C-1B72-0BBE-F3BFD984243F||8804|*/

                    }, function(error) { // callback to handle request error

                    }, function(notify) { // notify callback, can fire few times
                    });

                    var userData = Apperyio.get("dataStorage");
                    userData.current = success.data;
                    Apperyio.navigateTo("menu", {});
                    $scope.showSpinner2 = false;
                    console.log("********************" + $scope.user);
                })(success, $scope);
                //console.log("loginAPP");
                $scope.$apply();

            }, function(error) { // callback to handle request error
                alert("Incorrect username or password");
                console.log("error : ********************************* " + error);
                //$scope.showAlert("Incorrect username or password");

            }, function(notify) { // notify callback, can fire few times
            });
        };

        /**
         * @function changeLanguage
         * @param languageCode
         */
        $scope.changeLanguage = function(languageCode) {
            var $translate = Apperyio.get('$translate');
            $translate.use(languageCode);
            if (languageCode === 'ar') {

                $scope.languageCode = 'rtl';
            }
            if (languageCode === 'en') {
                $scope.languageCode = 'ltr';
            }
            $scope.$apply();

        };

        /**
         * @function showAlert
         * @param msg
         */
        $scope.showAlert = function(msg) {
            var $ionicPopup = Apperyio.get("$ionicPopup");
            var alertPopup = $ionicPopup.alert({
                title: 'Information',
                template: msg
            });
            alertPopup.then(function(res) {
                // you can do something here
            });

            $scope.showSpinner2 = false;
            $scope.$apply();
        };

        /**
         * @function notloged
         */
        $scope.notloged = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('Incorrect username or password', // message
            onConfirm, // callback to invoke with index of button pressed
            'Sorry', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * @function logint
         */
        $scope.logint = function() {
            var requestData = {};
            requestData = (function mapping5954($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('AppClientLogin.request.data', undefined, true);

                var user_scope = $scope.user;
                requestData.username = user_scope.username;
                requestData.password = user_scope.password;

                return requestData; /*|button_mapping|onbeforesend|84088ED6-FC9B-E07C-2DFF-337F2EA25A4E||5954|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("AppClientLogin")(requestData).then( /*|service_bookmark|bookmark|84088ED6-FC9B-E07C-2DFF-337F2EA25A4E||5730|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|84088ED6-FC9B-E07C-2DFF-337F2EA25A4E||3589|*/
                $scope.$apply();
                $scope.get_user_data();

                $scope.$apply();
            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function get_user_data
         */
        $scope.get_user_data = function() {
            var requestData = {};
            requestData = (function mapping4194($scope) {
                var requestData = {};
                requestData.params = Apperyio.EntityAPI('getuserdata_RESTService.request.query', undefined, true);

                var user_scope = $scope.user;
                requestData.params.username = user_scope.username;
                requestData.params.password = user_scope.password;

                return requestData; /*|button_mapping|onbeforesend|0812F0C4-B23A-1BE2-B508-2097643BDC18||4194|*/
            })($scope);

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("getuserdata_RESTService")(requestData).then( /*|service_bookmark|bookmark|0812F0C4-B23A-1BE2-B508-2097643BDC18||4530|*/

            function(success) { // success callback
                (function mapping4670(success, $scope) {
                    var user_scope = $scope.user;
                    var userid_scope = $scope.userid;
                    user_scope.sessionToken = success.data.sessionToken;
                    userid_scope = success.data._id;
                    $scope.user = user_scope;
                    $scope.userid = userid_scope;

                    sessionStorage.setItem("sessionToken", $scope.user.sessionToken);
                    var sessionToken = sessionStorage.getItem("sessionToken");
                    console.log(sessionToken);

                    sessionStorage.setItem("userid", $scope.userid);
                    var userid = sessionStorage.getItem("userid");
                    console.log(userid);
                    $scope.$apply();

                    Apperyio.navigateTo("menu", {});

                    /*|button_mapping|onsuccess|0812F0C4-B23A-1BE2-B508-2097643BDC18||4670|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * user controller variables
         */
        $scope.user = Apperyio.EntityAPI('User');
        $scope.language = Apperyio.EntityAPI('DataStorgage');
        $scope.showSpinner2 = Apperyio.EntityAPI('Boolean');
        $scope.languageCode = Apperyio.EntityAPI('String');
        $scope.usert = Apperyio.EntityAPI('DataStorgage');
        $scope.userName = Apperyio.EntityAPI('String');
        $scope.userid = Apperyio.EntityAPI('String');
    }

});