define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CLIENT_EDIT generated by Appery.io
     * @module CLIENT_EDIT
     */

    APP.controller('CLIENT_EDIT', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];
            console.log($scope.id);

            var requestData = {};
            requestData = (function mapping9373($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|85566ECB-D17A-A5C6-708D-F0C4EB7528A9||9373|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_get")(requestData).then( /*|service_bookmark|bookmark|85566ECB-D17A-A5C6-708D-F0C4EB7528A9||9885|*/

            function(success) { // success callback
                (function mapping3192(success, $scope) {
                    var CLIENT_scope = $scope.CLIENT;
                    CLIENT_scope = success;
                    $scope.CLIENT = CLIENT_scope; /*|button_mapping|onsuccess|85566ECB-D17A-A5C6-708D-F0C4EB7528A9||3192|*/
                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function FIND
         */
        $scope.FIND = function() {
            var requestData = {};
            requestData = (function mapping9674($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_find.request.data', undefined, true);

                var CLIENT_scope = $scope.CLIENT;
                requestData.where.NAME = CLIENT_scope.NAME;

                return requestData; /*|button_mapping|onbeforesend|DC46CA11-B972-7B21-E097-7686A88D55A8||9674|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_find")(requestData).then( /*|service_bookmark|bookmark|DC46CA11-B972-7B21-E097-7686A88D55A8||2840|*/

            function(success) { // success callback
                (function mapping7585(success, $scope) {
                    var CLIENTS_scope = $scope.CLIENTS;
                    CLIENTS_scope = success;
                    $scope.CLIENTS = CLIENTS_scope; /*|button_mapping|onsuccess|DC46CA11-B972-7B21-E097-7686A88D55A8||7585|*/

                    console.log("start looping");
                    for (var i = 0; i < $scope.CLIENTS.length; i++) {
                        console.log($scope.CLIENTS.DBID);
                        console.log($scope.CLIENTS[i].DBID);
                        if ($scope.CLIENTS[i].DBID != $scope.CLIENT.DBID) {
                            //alert("You have entered a name of another contact... Please try entering a different E-mail");
                            $scope.clientExists();
                            console.log("exists");
                            return;
                        }
                    }
                    console.log("Edit");
                    $scope.EDIT();
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            var requestData = {};
            requestData = (function mapping3034($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_update.request.data', undefined, true);

                var CLIENT_scope = $scope.CLIENT;
                requestData = CLIENT_scope;

                return requestData; /*|button_mapping|onbeforesend|244DDFD3-E369-83C5-466B-72729B6B5C0F||3034|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_update")(requestData).then( /*|service_bookmark|bookmark|244DDFD3-E369-83C5-466B-72729B6B5C0F||6637|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|244DDFD3-E369-83C5-466B-72729B6B5C0F||8722|*/

                //alert("Updated");
                $scope.editedAlert();
                Apperyio.navigateTo("CLIENT_DETAILS", {
                    '_id': $scope.id
                });
                $scope.$apply();

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function confirmEdit
         */
        $scope.confirmEdit = function() {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.FIND();
            }

            navigator.notification.confirm('Are you sure you want to submit updates?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Update', // title
            ['Yes', 'No'] // buttonLabels
            );
        };

        /**
         * @function editedAlert
         */
        $scope.editedAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('Record has bee updated', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['Yes'] // buttonLabels
            );
        };

        /**
         * @function clientExists
         */
        $scope.clientExists = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('You have entered a name of another contact... Please try entering a different E-mail', // message
            onConfirm, // callback to invoke with index of button pressed
            'Sorry', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * user controller variables
         */
        $scope.id = Apperyio.EntityAPI('String');
        $scope.CLIENT = Apperyio.EntityAPI('CLIENT');
        $scope.CLIENTS = Apperyio.EntityAPI('CLIENTS');
    }

});