define(['require', 'app'], function(require, APP) {

    /**
     * Controller for CLIENT_DETAILS generated by Appery.io
     * @module CLIENT_DETAILS
     */

    APP.controller('CLIENT_DETAILS', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         * @param _id
         */
        $scope.init = function(_id) {
            //On load screen logic
            $scope.state = false;
            var $routeParams = Apperyio.get("$routeParams");
            $scope.id = $routeParams['_id'];

            var requestData = {};
            requestData = (function mapping9638($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_get.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|ED8DF9E4-B657-A2BC-61E7-A25F3FB0D282||9638|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_get")(requestData).then( /*|service_bookmark|bookmark|ED8DF9E4-B657-A2BC-61E7-A25F3FB0D282||2465|*/

            function(success) { // success callback
                (function mapping7514(success, $scope) {
                    var CLIENT_scope = $scope.CLIENT;
                    CLIENT_scope = success;
                    $scope.CLIENT = CLIENT_scope; /*|button_mapping|onsuccess|ED8DF9E4-B657-A2BC-61E7-A25F3FB0D282||7514|*/

                    $scope.$apply();
                })(success, $scope);

            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function EDIT
         */
        $scope.EDIT = function() {
            Apperyio.navigateTo("CLIENT_EDIT", {
                '_id': $scope.id
            });
        };

        /**
         * @function DELETE
         */
        $scope.DELETE = function() {
            var requestData = {};
            requestData = (function mapping3859($scope) {
                var requestData = {};
                requestData = Apperyio.EntityAPI('CLIENT_delete.request.data', undefined, true);

                var id_scope = $scope.id;
                requestData.DBID = id_scope;

                return requestData; /*|button_mapping|onbeforesend|BEFB1815-DCD7-B958-FC41-B09DD4D23C9C||3859|*/
            })($scope);

            // read more about using rest services: https://devcenter.appery.io/documentation/angularjs/rest-service/ 
            Apperyio.get("CLIENT_delete")(requestData).then( /*|service_bookmark|bookmark|BEFB1815-DCD7-B958-FC41-B09DD4D23C9C||7909|*/

            function(success) { // success callback
                /*|button_mapping|onsuccess|BEFB1815-DCD7-B958-FC41-B09DD4D23C9C||1370|*/

                $scope.deletedAlert();
                Apperyio.navigateTo("CLIENT_LIST", {
                    '_id': $scope.id
                });
            }, function(error) { // callback to handle request error

            }, function(notify) { // notify callback, can fire few times
            });

        };

        /**
         * @function CONTACTS
         */
        $scope.CONTACTS = function() {
            Apperyio.navigateTo("Contacts", {
                '_id': $scope.id,
                'lorc': 'Client'
            });
        };

        /**
         * @function confirmDelete
         */
        $scope.confirmDelete = function() {
            function onConfirm(buttonIndex) {
                if (buttonIndex === 1) $scope.DELETE()();
            }

            navigator.notification.confirm('Are you sure you want to delete this?', // message
            onConfirm, // callback to invoke with index of button pressed
            'Delete', // title
            ['Yes', 'No'] // buttonLabels
            );
        };

        /**
         * @function deletedAlert
         */
        $scope.deletedAlert = function() {
            function onConfirm(buttonIndex) {

            }

            navigator.notification.confirm('This client has been deleted', // message
            onConfirm, // callback to invoke with index of button pressed
            'Success', // title
            ['OK'] // buttonLabels
            );
        };

        /**
         * @function EVENTS
         */
        $scope.EVENTS = function() {
            Apperyio.navigateTo("EVENT_LIST", {
                '_id': $scope.id,
                '_lorc': 'Client'
            });
        };

        /**
         * @function NOTES
         */
        $scope.NOTES = function() {
            Apperyio.navigateTo("ATTACHED_NOTE_LIST", {
                '_id': $scope.id,
                'type': 'Client'
            });
        };

        /**
         * user controller variables
         */
        $scope.CLIENT = Apperyio.EntityAPI('CLIENT');
        $scope.id = Apperyio.EntityAPI('String');
    }

});